apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-composer.fullname" . }}-config
  labels:
    {{- include "mcp-composer.labels" . | nindent 4 }}
data:
  mcp_servers.json: |
{{ toJson .Values.config | indent 4 }}
